---
title: "Simple document"
output: github_document
---

```{r,echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## import some data

I want to immort'FAS-litter.csv"

```{r}
litters_df = read.csv("data/FAS_litters.csv")

read.csv("/Users/chris/Desktop/data_wrangling-1/data/FAS_litters.csv") #but  never use this

#Yay now I imported the dataset, now I want better names.
```


```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```
Yay! now i have bettr names lets look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r}
eval=FALSE
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```


## arguments in 'read_csv'

```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
```
## parsing column
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
litters_data
```


# reading from excel


reading MLB data
```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

LotR words is next
```{r}
fellow_df = read_excel("data/LotR_Words.xlsx",range = "B3:D6")
```
## read a SAS file
```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

pulse_df

